site_name: House Price Quoting App
#
site_author: Nikolaos Mavromatis
repo_url: https://github.com/nikolaos-mavromatis/ames_house_price_prediction
repo_name: nikolaos-mavromatis/house-price-quoting-app
theme:
  name: material
  language: en
  font:
    text: Avenir Next
  icon:
    logo: material/home
    repo: fontawesome/brands/github
